import json

def match_words_and_labels(data):
    matched_data = []

    for example in data:
        sentence = example.get("sentence", "")
        labels = example.get("labels", [])

        # Split the sentence into words
        words = sentence.split()

        # Ensure the number of words and labels match
        if len(words) != len(labels):
            print(f"Error: Mismatch between the number of words ({len(words)}) and labels ({len(labels)}) in the sentence:\n{sentence}\n")
            continue

        # Match each word with its label
        word_label_pairs = list(zip(words, labels))
        matched_data.append({"sentence": sentence, "word_label_pairs": word_label_pairs})

    return matched_data

'''
### json_data is input dictionary (json format) to map labels in the sentence which is generated by ChatGPT 

# This exmple will return  
>>> Error: Mismatch between the number of words (26) and labels (29) in the sentence:
>>> Nestled in the majestic Himalayan range, straddling the border between Nepal and Tibet, this colossal mountain has captured the imagination of adventurers and climbers for centuries.
>>> 
>>> Sentence: Mount Everest, towering at an awe-inspiring height of 29,032 feet (8,848 meters), is the highest peak on Earth.
>>> Word-Label Pairs: [('Mount', 'B-MOUNTAIN'), ('Everest,', 'I-MOUNTAIN'), ('towering', 'O'), ('at', 'O'), ('an', 'O'), ('awe-inspiring', 'O'), ('height', 'O'), ('of', 'O'), ('29,032', 'O'), ('feet', 'O'), ('(8,848', 'O'), ('meters),', 'O'), ('is', 'O'), ('the', 'O'), ('highest', 'O'), ('peak', 'O'), ('on', 'O'), ('Earth.', 'O')]
'''

json_data = [
    {
      "sentence": "Mount Everest, towering at an awe-inspiring height of 29,032 feet (8,848 meters), is the highest peak on Earth.",
      "labels": ["B-MOUNTAIN", "I-MOUNTAIN", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]
    },
    {
      "sentence": "Nestled in the majestic Himalayan range, straddling the border between Nepal and Tibet, this colossal mountain has captured the imagination of adventurers and climbers for centuries.",
      "labels": ["O", "O", "O", "O", "B-MOUNTAIN", "I-MOUNTAIN", "O", "O",  "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]
    },
]

# Match words with labels
matched_data = match_words_and_labels(json_data)

# Print the matched data
for example in matched_data:
    print("Sentence:", example["sentence"])
    print("Word-Label Pairs:", example["word_label_pairs"])
    print()
